name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  test-build-release:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Install dependencies
      run: make promu
    - name: Run tests
      run: make
    - name: Download github-release
      run: |
        mkdir -v -p ${HOME}/bin
        curl -L 'https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C ${HOME}/bin
        echo '${HOME}/bin' >> ${GITHUB_PATH}
    - name: Build binaries
      run: |
        promu crossbuild -v -p linux/amd64
        promu checksum .tarballs
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build Docker image and push
      run: docker buildx build -t ricardoag/${{ github.repository }}:${{ github.ref_name }} . --push

  