name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  test-build-release:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Run tests
      run: make build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build Docker image and push
      run: docker buildx build -t ricardoag/${{ github.repository }}:${{ github.ref_name }} . --push

  